# Generated by Django 4.0.1 on 2022-01-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('costperitem', models.BigIntegerField()),
                ('stockquantity', models.BigIntegerField()),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=89, null=True)),
            ],
        ),
    ]
